# codigo_mapper.py

# Mapeo de código → nombre del servicio
codigo_a_servicio = {
    "AT001": "ATV",
    "BA002": "Baby Sitters",
    "BA003": "Bartender",
    "BE004": "Beach Club",
    "BO005": "Boat Lunch Box",
    "BO006": "Bodyguard",
    "CA007": "Cake",
    "CR008": "Car Rental",
    "CT009": "Cartagena Tours",
    "CB010": "Chef BBQ",
    "CD011": "Chef Dinner",
    "CL012": "Chef Lunch at the villa",
    "CC013": "Chef catering",
    "CO014": "Chef on board",
    "CL015": "Cleaning",
    "CO016": "Concierge",
    "CO017": "Cook",
    "DJ018": "DJ",
    "DC019": "Dance Class",
    "DR020": "Driver",
    "FL021": "FlyBoard",
    "GO022": "Golf",
    "GR023": "Groceries",
    "GY024": "Gym",
    "HM025": "Hair & Makeup",
    "HE026": "Helicopter",
    "IV027": "IV Therapy",
    "IH028": "Island Hopping",
    "LA029": "Laundry",
    "LD030": "Liquor and Drinks",
    "MA031": "Massage",
    "MT032": "Medellin Tours",
    "MT033": "Mexican Tours",
    "ND034": "NightClub (Deposit)",
    "NF035": "Non - Food Purchases",
    "OC036": "O - Chef",
    "OS037": "Other services",
    "PH038": "Photographer",
    "PF039": "Private Flight",
    "RE040": "Rentals",
    "SD041": "Scuba Diving",
    "SE042": "Services",
    "SN043": "Snorkel",
    "SP044": "Spa",
    "TI045": "Tickets",
    "TR046": "Transport",
    "WR047": "Wrestling",
    "YO048": "Yoga"
}

# Mapeo de nombre del servicio → ID de QuickBooks
servicio_a_id = {
    "ATV": "28",
    "Baby Sitters": "30",
    "Bartender": "1",
    "Beach Club": "38",
    "Boat Lunch Box": "33",
    "Bodyguard": "2",
    "Cake": "4",
    "Car Rental": "5",
    "Cartagena Tours": "41",
    "Chef BBQ": "11",
    "Chef Dinner": "43",
    "Chef Lunch at the villa": "6",
    "Chef catering": "7",
    "Chef on board": "8",
    "Cleaning": "9",
    "Concierge": "10",
    "Cook": "12",
    "DJ": "13",
    "Dance Class": "14",
    "Driver": "15",
    "FlyBoard": "16",
    "Golf": "18",
    "Groceries": "17",
    "Gym": "19",
    "Hair & Makeup": "21",
    "Helicopter": "22",
    "IV Therapy": "23",
    "Island Hopping": "25",
    "Laundry": "26",
    "Liquor and Drinks": "27",
    "Massage": "29",
    "Medellin Tours": "32",
    "Mexican Tours": "31",
    "NightClub (Deposit)": "37",
    "Non - Food Purchases": "34",
    "O - Chef": "3",
    "Other services": "35",
    "Photographer": "36",
    "Private Flight": "39",
    "Rentals": "40",
    "Scuba Diving": "42",
    "Services": "24",
    "Snorkel": "44",
    "Spa": "45",
    "Tickets": "46",
    "Transport": "47",
    "Wrestling": "48",
    "Yoga": "49"
}

# Función que devuelve el ID final que se necesita para la factura
from servicio_a_id import servicio_a_id

def obtener_item_id_desde_codigo(codigo):
    nombre_servicio = codigo_a_servicio.get(codigo)
    return servicio_a_id.get(nombre_servicio, "1")  # "1" como fallback para pruebas
